# Generated by Django 5.2.11 on 2026-02-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price_from', models.CharField(max_length=50, verbose_name='Precio desde')),
                ('image', models.ImageField(upload_to='catering/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pack Catering',
                'verbose_name_plural': 'Packs Catering',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Imagen Galería',
                'verbose_name_plural': 'Imágenes Galería',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Titular Hero')),
                ('hero_subtitle', models.TextField(verbose_name='Subtítulo Hero')),
                ('cta_text', models.CharField(default='Contactar por WhatsApp', max_length=50, verbose_name='Texto Botón CTA')),
                ('services_title', models.CharField(default='Nuestros Servicios', max_length=100, verbose_name='Título Servicios')),
                ('catering_title', models.CharField(default='Catering para Eventos', max_length=100, verbose_name='Título Catering')),
                ('gallery_title', models.CharField(default='Galería', max_length=100, verbose_name='Título Galería')),
            ],
            options={
                'verbose_name': 'Contenido Home',
                'verbose_name_plural': 'Contenido Home',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('whatsapp_message', models.TextField(default='Hola 😊 Me gustaría información sobre catering.', verbose_name='Mensaje predefinido WhatsApp')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('hours', models.TextField(verbose_name='Horarios')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
